In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.4.4


# np.array() to create ndarray

In [11]:
arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# .ndim to display number of dimension

1. 0-D arrays = Scalar 
2. 1-D arrays = Vector e.g (row vector, column vector)
3. 2-D arrays = Matrix e.g (CSV, excel spreadsheet)
4. 3-D arrays = Tensors e.g (RGB colors)

In [101]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [16]:
lst = np.arange(100000)
print(lst.ndim)

1


## Shortcuts for creating ndarrays

In [3]:
arr = np.ones((5,5)) # Row, Column

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
arr = np.eye(2,2) # Creating diagonal ones
print(arr)

[[1. 0.]
 [0. 1.]]


In [8]:
arr = np.zeros((2,2)) # Creating zeros 

In [6]:
arr = np.diag((-1,-3,-5)) # set diagonal values

In [11]:
print(arr)

[[-1  0  0]
 [ 0 -3  0]
 [ 0  0 -5]]


## Np array indexing

In [58]:
print(arr[1,1]) #[row,column]

-3


## Transpose array

In [12]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

print(arr.T) # T attribute for tranpose 
print(np.transpose(arr)) # tranpose method

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Slicing n-D arrays

In [13]:
print(arr)

print(f"Slicing the second row of arr: {arr[1,1:]} ") # or arr[1][1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Slicing the second row of arr: [5 6] 


In [72]:
print(arr[:,2]) # accessing 2nd elements of each row

[3 6 9]


In [73]:
# Inversing array
arr = np.array([1,2,3,4,5])

print(arr[::-1])

[5 4 3 2 1]


## Data types in Numpy

In [76]:
print(arr[0].dtype)
print(type(arr[0]))

int64
<class 'numpy.int64'>


In [84]:
arr = np.array([1,2,3,4,5], dtype="S") # set to ASCII dtype
arr = np.array([1,2,3,4,5,], dtype="i4")

print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


## Data types conversion

In [89]:
arr = np.array([2.484,3.142,6.92])
arr = arr.astype('i') # covnert float to int

print(arr)
print(arr.dtype)

[2 3 6]
int8


## View vs Copy array

* Changes to ***copied array*** doesn't affect the ***original array*** and vice versa.
* Chnages to ***viewd array*** affect the ***original array*** and vice versa.

In [96]:
# copy
arr = np.array([1,2,3,4,5])

copied_array = arr.copy()
print("Before changes")
print(f"Original: {arr}\nCopied: {copied_array}")

print()
#changes
arr[0] = 10
print("After changes")
print(f"Original: {arr}\nCopied: {copied_array}")

Before changes
Original: [1 2 3 4 5]
Copied: [1 2 3 4 5]

After changes
Original: [10  2  3  4  5]
Copied: [1 2 3 4 5]


In [99]:
# view (Same as x = arr concept)
arr = np.array([1,2,3,4,5])

x = arr.view()
print("Before changes")
print(f"Original: {arr}\nCopied: {x}")

print()
#changes
x[0] = 10
print("After changes")
print(f"Original: {arr}\nCopied: {x}")

Before changes
Original: [1 2 3 4 5]
Copied: [1 2 3 4 5]

After changes
Original: [10  2  3  4  5]
Copied: [10  2  3  4  5]


# Shape vs Dimension

* Shape (.shape): The length of each individual axis.
* Dimension (.ndim): The number of axes (dimensions).

In [104]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr)
print("Dimension: ",arr.ndim)
print("Shape: ",arr.shape) # (row,column)

[[1 2 3]
 [4 5 6]]
Dimension:  2
Shape:  (2, 3)


## Reshaping array

In [110]:
arr = np.arange(16)

print(arr)
print(arr.shape)
print()

# reshape
arr = arr.reshape(4,-1) # reshape to form a 4x4 matrix
print(arr)
print(arr.shape)


# n-d array
print()
arr = arr.reshape(2,4,2) # Tip: 2*4*2 = 16 = Total number of elements 
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


## unknown dimension

* -1 = unspecified (Computer will automatically allocate to set the value)
* **-1** cannot be used more than once.

In [123]:
arr = np.arange(12)
print(arr)

print("New array")
new_arr = arr.reshape(2,3,-1)
print(new_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
New array
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


## Flattenning (Reshaping n-d array into 1-D array)

In [128]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr)
print(arr.shape)
print(arr.ndim)

print("\nFlatten the array")
arr = arr.reshape(-1)
print(arr)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2

Flatten the array
[1 2 3 4 5 6]
(6,)
1


## Iterating Arrays using nditer()

* Iterating on each **scalar** element

In [14]:
arr = np.array([[[1,2],[3,4]], [[41,5],[6,7]], [[8,9],[10,11]]])

for x in np.nditer(arr[:,1::2]):
    print(x)

3
4
6
7
10
11


## Enumerateed Iteration using ndenumerate()

In [147]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr)
for index, value in np.ndenumerate(arr):
    print(index,value)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


## Joining/concatenate() array

* axis = 0: Vertical concatenatation **(Default)** = np.vstack()
* axis = 1: adjacent (Horizontal) concatenation  = np.hstack()
* axis = None; Flatten (1-D) array

In [28]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

arr2 = np.array([[7,8,9],
                [10,11,12]])
con_arr = np.concatenate((arr1,arr2), axis=1)
print(con_arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [27]:
new_arr = np.vstack((arr1,arr2)) 
# Same as np.concatenate(, axis=0) plus creating new dim

print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
h_arr = np.hstack((arr1,arr2))
print(h_arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Splitting array

In [30]:
sarr = np.arange(12)
print(sarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [36]:
arr_list = np.array_split(sarr,2)
print(arr_list)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]


In [40]:
for i in range(len(arr_list)):
    print(arr_list[i])

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]


 ## Filtering array + Sorting

* Def: extract values which meet the specified conditions in the (Hard-coded) boolean index list
* ***Required***: Boolean index list (Same size with original array)

In [48]:
arr = np.array([1,2,3,4,5])
bool_cond = [True,False,True,False,True]

# Filtering 
filtered_arr = arr[bool_cond]
print(filtered_arr)

# ascending order
ascend_arr = np.sort(arr)
# descending order
descend_arr = np.sort(arr)[::-1]
print(f"Ascending order: {ascend_arr}\nDescending order: {descend_arr}")

[1 3 5]
Ascending order: [1 2 3 4 5]
Descending order: [5 4 3 2 1]


## Filter arry (Conditional bool)

In [52]:
filt_arr = []
for x in arr:
    if (x % 2 != 0): # odd only
        filt_arr.append(True)
    else:
        filt_arr.append(False)

print(f"Bool index list: {filt_arr}")

# filter 
new_arr = arr[filt_arr]
print(f"Filtered array: {new_arr}")

Bool index list: [True, False, True, False, True]
Filtered array: [1 3 5]


In [55]:
# New method
new_arr = arr[arr %  2 != 0]
print(new_arr)

[1 3 5]
